"""add action_item_completions table

Revision ID: 25807bbe8aab
Revises: 99deec048618
Create Date: 2026-05-29 11:27:53.459055

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '25807bbe8aab'
down_revision: Union[str, None] = '99deec048618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_item_completions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('action_text', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('officer_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_item_completions')
    # ### end Alembic commands ###
